import React from 'react';
import { Zap, BookOpen, AlertTriangle, Code, Video, CheckCircle2, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function RecommendationPanel() {
  const navigate = useNavigate();

  const recommendations = [
    {
      id: 'rec-1',
      title: 'Continue Lesson',
      subject: 'Dynamic Programming & Memoization',
      detail: 'Lesson 9 of 12 in Advanced Algorithms',
      icon: <BookOpen className="w-4 h-4 text-black" />,
      actionText: 'Resume Lesson',
      path: '/learn/adv-algorithms/dynamic-programming/dp-introduction'
    },
    {
      id: 'rec-2',
      title: 'Practice Weak Topic',
      subject: 'Heap Priority Queues',
      detail: 'Accuracy is 72% in recent practice sets',
      icon: <AlertTriangle className="w-4 h-4 text-black" />,
      actionText: 'Practice Set',
      path: '/practice'
    },
    {
      id: 'rec-3',
      title: 'Solve Coding Challenge',
      subject: 'Longest Palindromic Substring',
      detail: 'Medium • String Processing • +150 XP',
      icon: <Code className="w-4 h-4 text-black" />,
      actionText: 'Open CodeLab',
      path: '/codelab'
    },
    {
      id: 'rec-4',
      title: 'Attempt Interview',
      subject: 'System Design Mock Rehearsal',
      detail: 'Proctoring & Gaze Stability Active',
      icon: <Video className="w-4 h-4 text-black" />,
      actionText: 'Start Interview',
      path: '/interview'
    },
    {
      id: 'rec-5',
      title: 'Complete Daily Goal',
      subject: '3 of 4 Daily Micro-Tasks Finished',
      detail: 'Complete 1 more item for +50 Bonus XP',
      icon: <CheckCircle2 className="w-4 h-4 text-black" />,
      actionText: 'View Goals',
      path: '/dashboard'
    }
  ];

  return (
    <div className="p-6 md:p-8 rounded-[2.5rem] border border-slate-200/80 bg-white mb-8 shadow-xs">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-lg font-bold font-display text-black flex items-center gap-2">
            <Zap className="w-5 h-5 text-black" /> Intelligent Action Plan
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">Prioritized recommendations generated by your AI Coach based on your skill roadmap.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-6 rounded-[1.75rem] bg-white border border-slate-200/80 hover:border-slate-300 transition-all duration-300 flex flex-col justify-between group shadow-xs"
          >
            <div>
              <span className="text-[10px] font-black uppercase tracking-wider px-3 py-1 rounded-full bg-slate-100 border border-slate-200 text-black inline-flex items-center gap-1.5 mb-3">
                {rec.icon}
                {rec.title}
              </span>

              <h3 className="text-sm font-bold text-black group-hover:text-slate-600 transition-colors mb-1">
                {rec.subject}
              </h3>
              <p className="text-xs text-slate-500 font-medium leading-relaxed mb-4">
                {rec.detail}
              </p>
            </div>

            <button
              onClick={() => navigate(rec.path)}
              className="w-full py-3 rounded-full bg-black text-white hover:bg-slate-800 font-bold text-xs transition-all flex items-center justify-center gap-1.5 group/btn"
            >
              <span>{rec.actionText}</span>
              <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover/btn:translate-x-1" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
