import React from 'react';
import { Sparkles, BookOpen, AlertTriangle, Code, Video, CheckCircle2, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function RecommendationPanel() {
  const navigate = useNavigate();

  const recommendations = [
    {
      id: 'rec-1',
      title: 'Continue Lesson',
      subject: 'Dynamic Programming & Memoization',
      detail: 'Lesson 9 of 12 in Advanced Algorithms',
      icon: <BookOpen className="w-4 h-4 text-indigo-600" />,
      tagColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
      actionText: 'Resume Lesson',
      path: '/learn/adv-algorithms/dynamic-programming/dp-introduction'
    },
    {
      id: 'rec-2',
      title: 'Practice Weak Topic',
      subject: 'Heap Priority Queues',
      detail: 'Accuracy is 72% in recent practice sets',
      icon: <AlertTriangle className="w-4 h-4 text-amber-600" />,
      tagColor: 'bg-amber-50 text-amber-700 border-amber-200',
      actionText: 'Practice Set',
      path: '/practice'
    },
    {
      id: 'rec-3',
      title: 'Solve Coding Challenge',
      subject: 'Longest Palindromic Substring',
      detail: 'Medium • String Processing • +150 XP',
      icon: <Code className="w-4 h-4 text-cyan-600" />,
      tagColor: 'bg-cyan-50 text-cyan-700 border-cyan-200',
      actionText: 'Open CodeLab',
      path: '/codelab'
    },
    {
      id: 'rec-4',
      title: 'Attempt Interview',
      subject: 'System Design Mock Rehearsal',
      detail: 'Proctoring & Gaze Stability Active',
      icon: <Video className="w-4 h-4 text-emerald-600" />,
      tagColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
      actionText: 'Start Interview',
      path: '/interview'
    },
    {
      id: 'rec-5',
      title: 'Complete Daily Goal',
      subject: '3 of 4 Daily Micro-Tasks Finished',
      detail: 'Complete 1 more item for +50 Bonus XP',
      icon: <CheckCircle2 className="w-4 h-4 text-purple-600" />,
      tagColor: 'bg-purple-50 text-purple-700 border-purple-200',
      actionText: 'View Goals',
      path: '/dashboard'
    }
  ];

  return (
    <div className="glass p-6 md:p-8 rounded-[2.5rem] border border-slate-200/50 mb-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-lg font-bold font-display text-slate-900 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-indigo-600 animate-pulse" /> Intelligent Action Plan
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">Prioritized recommendations generated by your AI Coach based on your skill roadmap.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-5 rounded-2xl bg-white border border-slate-200/60 hover:border-indigo-400/40 hover:shadow-md transition-all duration-300 flex flex-col justify-between group"
          >
            <div>
              <span className={`text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-full border inline-flex items-center gap-1.5 mb-3 ${rec.tagColor}`}>
                {rec.icon}
                {rec.title}
              </span>

              <h3 className="text-sm font-bold text-slate-900 group-hover:text-indigo-600 transition-colors mb-1">
                {rec.subject}
              </h3>
              <p className="text-xs text-slate-500 font-medium leading-relaxed mb-4">
                {rec.detail}
              </p>
            </div>

            <button
              onClick={() => navigate(rec.path)}
              className="w-full py-2.5 rounded-xl bg-slate-900 text-white hover:bg-indigo-600 font-bold text-xs transition-all flex items-center justify-center gap-1.5 group/btn"
            >
              <span>{rec.actionText}</span>
              <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover/btn:translate-x-1" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
